version: '3'
services:
  nginx:
    build:
      args:
        nginx_port: 80
        nginx_version: ${NGINX_VERSION}
        nginx_vhost_name: ${NGINX_VHOST_NAME}
      context: ./docker/nginx
    container_name: xml-cart-nginx
    depends_on:
      - php-fpm
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./src/xml-cart:/var/www/xml-cart:cached
    networks:
      - 'xml-cart'

  php-fpm:
    build:
      args:
        php_version: ${PHP_VERSION}
      context: ./docker/php-fpm
    container_name: xml-cart-php-fpm
    env_file:
      - .env
    volumes:
      - ./src/xml-cart:/var/www/xml-cart:cached
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:cached
    networks:
      - 'xml-cart'

networks:
  xml-cart:
